markdownSlides:
#  image: busybox:latest
  stage: deploy
  script:
    - echo "copy images..."
    - cp docs/*.png docs/*.jpg docs/*.svg /var/www/courses.fmsoft.cn/best-practices-of-c/assets -f
    - echo "copy HTML files..."
    - cp docs/*.html /var/www/courses.fmsoft.cn/best-practices-of-c/ -f
    - echo "copy markdown files..."
    - cp docs/*.md /var/www/courses.fmsoft.cn/best-practices-of-c/gitlab/ -f
    - echo "done"
  only:
    refs:
      - master
    changes:
      - docs/*

